CREATE TABLE IF NOT EXISTS `CATEGORIES`
(
  `ID`          BIGINT(20)  NOT NULL AUTO_INCREMENT,
  `NAME`        VARCHAR(60) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `unique` (`NAME` ASC)
);

CREATE TABLE IF NOT EXISTS `TV_SHOWS`
(
  `ID`          	BIGINT(20)    NOT NULL AUTO_INCREMENT,
  `NAME` 			VARCHAR(256)  NOT NULL,
  `SHORT_DESC` 		VARCHAR(256)  NULL DEFAULT NULL,
  `LONG_DESC` 		VARCHAR(2048) NULL DEFAULT NULL,
  `YEAR` 			YEAR(4) 	  NOT NULL,
  `RECOMMENDED_AGE` TINYINT 	  NOT NULL,
  `CATEGORY_ID` 	BIGINT(20)    NOT NULL,
  `ADVERTISING` 	VARCHAR(256)  NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_TV_SHOWS_CATEGORY_ID`
    FOREIGN KEY (CATEGORY_ID) REFERENCES `CATEGORIES` (ID)
);

CREATE TABLE IF NOT EXISTS `SEASONS`
(
  `ID`          BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `NUMBER` 		TINYINT 	 NOT NULL,
  `NAME` 		VARCHAR(256) NOT NULL,
  `TV_SHOW_ID`  BIGINT(20)   NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_SEASONS_TV_SHOW_ID`
    FOREIGN KEY (TV_SHOW_ID) REFERENCES `TV_SHOWS` (ID)
);

CREATE TABLE IF NOT EXISTS `CHAPTERS`
(
  `ID`          BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `NUMBER` 		TINYINT 	 NOT NULL,
  `NAME` 		VARCHAR(256) NOT NULL,
  `DURATION` 	TINYINT 	 NOT NULL,
  `SEASON_ID`  BIGINT(20)   NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_CHAPTERS_SEASON_ID`
    FOREIGN KEY (SEASON_ID) REFERENCES `SEASONS` (ID)
);


CREATE TABLE IF NOT EXISTS `ACTORS`
(
  `ID`          BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `NAME` 		VARCHAR(256) NOT NULL,
  `SURNAME`		VARCHAR(256) NOT NULL,  
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_ACTORS_TV_SHOWS_ID`
    FOREIGN KEY (TV_SHOW_ID) REFERENCES `TV_SHOWS` (ID)

);

CREATE TABLE IF NOT EXISTS `CHAPTERS_ACTORS`
(
   `ID`          	BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CHAPTER_ID`      BIGINT(20) NOT NULL,
  `ACTOR_ID` 		BIGINT(20) NOT NULL,   
  FOREIGN KEY (`CHAPTER_ID`) REFERENCES `CHAPTERS` (ID) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (`ACTOR_ID`) REFERENCES `ACTORS` (ID) ON DELETE RESTRICT ON UPDATE CASCADE,
  PRIMARY KEY (`ID`)  
);

CREATE TABLE IF NOT EXISTS `AWARDS`
(
  `ID`          BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `NAME` 		VARCHAR(256) NOT NULL,
  `YEAR`		YEAR(4) NOT NULL,  
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_AWARDS_TV_SHOWS_ID`
    FOREIGN KEY (TV_SHOW_ID) REFERENCES `TV_SHOWS` (ID)
);

CREATE TABLE IF NOT EXISTS `TV_SHOWS_AWARDS`
(
   `ID`          BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `TV_SHOWS_ID`      BIGINT(20) NOT NULL,
  `AWARDS_ID` 		BIGINT(20) NOT NULL,   
  `YEAR`		YEAR(4) NOT NULL, 
  FOREIGN KEY (`TV_SHOWS_ID`) REFERENCES `TV_SHOWS` (ID) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (`AWARDS_ID`) REFERENCES `AWARDS` (ID) ON DELETE RESTRICT ON UPDATE CASCADE,
  PRIMARY KEY (`ID`)
);

