INSERT INTO CATEGORIES(ID, NAME) VALUES 
	(3, 'ACCIÓN');
	
INSERT INTO TV_SHOWS(ID, NAME, SHORT_DESC, LONG_DESC, YEAR, RECOMMENDED_AGE) VALUES 
	(1, 'Juego de tronos', 'Descripción corta', 'Descripción larga', '2012', 16),
	(2, 'American horror Story', NULL, NULL, '2010', 16);
	
INSERT INTO SEASONS(ID, NUMBER, NAME, TV_SHOW_ID) VALUES 
	(1, 1, 'One', 1),
	(2, 1, 'One', 2);
	
INSERT INTO CHAPTERS(ID, NUMBER, NAME, DURATION, SEASON_ID) VALUES 
	(1, 1, 'Chapter 1', 43, 1),
	(2, 1, 'Chapter 1', 43, 2);
	
INSERT INTO ACTORS(ID, NAME, SURNAME, DAY_OF_BIRTH) VALUES 
	(1, 'PETER', 'DINKLAGE', '1980-05-25'),
	(2, 'EMILIA', 'CLARKE', '1989-03-29');

INSERT INTO CHAPTERS_ACTORS(ID, CHAPTER_ID, ACTOR_ID) VALUES
	(1, 1, 1),
	(2, 2, 2);

INSERT INTO CATEGORIES_TV_SHOWS(ID, CATEGORY_ID, TV_SHOW_ID) VALUES
	(1, 3, 1),
	(2, 3, 2);
	
